### ISSUE TITLE
[Feature request] export into one single Markdown file

### ISSUE THREAD

**Issue by Dricc123** [jan-mate/Journalize#6]
What do you think of implementing .md export as one file?
It keeps the readability and searchability high, so it's good for people who dont want to export it to different apps!

**Comment by jan-mate** [comment]
I've added option to export as a single markdown file v1.2.0. 
Feel free to provide feedback on the layout, after rendering it will look like this:

---

modified: 2024-10-20T06:39:00.549

created: 2024-10-20T06:38:58.612

coords: N/A

last_coords: 49.1255 10.525918

tags: Emotion


This is the content of the entry

---

modified: 2024-10-20T06:38:57.863

created: 2024-10-20T06:38:55.577

coords: 69.1337 42.06969

last_coords: 49.1255 10.525918

tags: Do, φ, Quote, Book, Emotion


this is the content

---

**Comment by Dricc123** [comment]
It works great! Thank you!
Any reason to double-space the metadata? It's just a detail, I know.

**Comment by jan-mate** [comment]
I think double spacing makes it more readable because when rendered it will be on different lines. I thought about using `<br>` as newline, but many markdown renderers don't support it.
This is how it will look for many renderes if  theres not double enter:

---
modified: 2024-10-20T06:39:00.549 created: 2024-10-20T06:38:58.612 coords: N/A last_coords: 49.1255 10.525918 tags: Emotion

This is the content of the entry
